const soups = [
    {
        keyword: 'warm',
        name: 'Теплый',
        price: 7,
        desc: 'Для первого визита — идеально.',
        category: 'soup',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/warm.jpg',
        kind: '0cent',
    },
    {
        keyword: 'house',
        name: 'Из Семи Халуп',
        price: 10,
        desc: 'Наестся и тот, у кого нет желудка.',
        category: 'soup',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/seven houses.png',
        kind: '40cent',
    },
    {
        keyword: 'pumpkin',
        name: 'Тыквенный',
        price: 5,
        desc: 'Согревает даже сквозь временные сдвиги.',
        category: 'soup',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/helloween.png',
        kind: '0cent',
    },
    {
        keyword: 'skorb',
        name: 'Скоблянка Древнего Поля',
        price: 11,
        desc: 'Тоже из времён, когда суп варили в ямах.',
        category: 'soup',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/soup4.png',
        kind: '40cent',
    },
    {
        keyword: 'algorithm',
        name: 'Пищевой алгоритм №17',
        price: 15,
        desc: 'Любим в тех столетиях, где еда — просто код.',
        category: 'soup',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/soup5.png',
        kind: '130cent',
    },
    {
        keyword: '3',
        name: 'Вакуумный борщ',
        price: 8,
        desc: 'Подойдет ностальгирующему пришельцу.',
        category: 'soup',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/soup6.png',
        kind: '130cent',
    }
]

const meals = [
    {
        keyword: 'lapsha',
        name: 'Лапша с дымком',
        price: 6,
        desc: 'Как будто откуда-то из дома, даже если дома нет.',
        category: 'meal',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dish1.png',
        kind: 'meat',
    },
    {
        keyword: 'plov',
        name: 'Плов "Переход"',
        price: 9,
        desc: 'Плов, который собрал лучшее со всех дорог.',
        category: 'meal',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dish2.png',
        kind: 'meat',
    },
    {
        keyword: 'road',
        name: 'Дом и дорога',
        price: 8,
        desc: 'Тепло для усталых путешественников.',
        category: 'meal',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dish3.png',
        kind: 'vegetarian',
    },
    {
        keyword: 'korni',
        name: 'Корни',
        price: 12,
        desc: 'Будто всё лето впиталось в ложку.',
        category: 'meal',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dish4.png',
        kind: 'vegetarian',
    },
    {
        keyword: 'human_meat',
        name: 'Мясо из Никуда',
        price: 20,
        desc: 'Оно просто есть. Никто не спрашивает, откуда оно.',
        category: 'meal',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dish5.png',
        kind: 'cannibal',
    },
    {
        keyword: 'tongue',
        name: 'Язык Дипломата',
        price: 14,
        desc: 'Слишком вежлив, чтобы отказаться. Слишком вкусен, чтобы забыть.',
        category: 'cannibal',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dish6.png',
        kind: 'cannibal',
    }
]

const drinks = [
    {
        keyword: 'sbiten',
        name: 'Сбитень',
        price: 8,
        desc: 'Медовый напиток с травами.',
        category: 'drink',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/drink1.jpg',
        kind: 'sober',
    },
    {
        keyword: 'koren',
        name: 'Пенный корень',
        price: 11,
        desc: 'Его пили до первой мировой и после третьей.',
        category: 'drink',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/drink2.jpg',
        kind: 'alcohol'
    },
    {
        keyword: 'water',
        name: 'Вода прогалины',
        price: 4,
        desc: 'Ты поймёшь, как только попробуешь.',
        category: 'drink',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/drink3.png',
        kind: 'sober',
    },
    {
        keyword: 'fog',
        name: 'Тёплый туман',
        price: 7,
        desc: 'Без градуса, но с эффектом.',
        category: 'drink',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/drink4.png',
        kind: 'sober',
    },
    {
        keyword: 'ash',
        name: 'Зола и дым',
        price: 12,
        desc: 'Вкус прошлого, горечи, но с теплом.',
        category: 'drink',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/drink5.png',
        kind: 'alcohol',
    },
    {
        keyword: 'echo',
        name: 'Эхо перепоя',
        price: 17,
        desc: 'Не столько пьёшь, сколько вспоминаешь, как это было.',
        category: 'drink',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/drink6.png',
        kind: 'alcohol',
    },
];

const salads = [
    {
        keyword: 'meteor_mix',
        name: 'Метеоритный микс',
        price: 3,
        desc: 'Греет, как трение в атмосфере.',
        category: 'salad',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/salad1.png',
        kind: 'mega',
    },
    {
        keyword: 'tension',
        name: 'Натяжение вкуса',
        price: 1,
        desc: 'Вкус раскрывается при колебаниях.',
        category: 'salad',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/salad2.png',
        kind: 'micro',
    },
    {
        keyword: 'rootmix',
        name: 'Корневая смесь',
        price: 2,
        desc: 'Хрустит, пахнет теплом земли.',
        category: 'salad',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/salad3.png',
        kind: 'macro',
    },
    {
        keyword: 'nightgreen',
        name: 'Ночная Зелень',
        price: 4,
        desc: 'Светится в темноте, но съедобен.',
        category: 'salad',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/salad4.png',
        kind: 'macro',
    },
    {
        keyword: 'fieldbite',
        name: 'Полевая Жеванка',
        price: 3,
        desc: 'Нежный, будто дожди в мае.',
        category: 'salad',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/salad5.png',
        kind: 'macro',
    },
    {
        keyword: 'wanderer',
        name: 'Салат Скитальца',
        price: 6,
        desc: 'Из всего, что можно найти.',
        category: 'salad',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/salad6.png',
        kind: 'macro',
    },
]

const desserts = [
    {
        keyword: 'zimka',
        name: 'Зимка',
        price: 9,
        desc: 'После него внутри идёт снег.',
        category: 'dessert',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dessert1.png',
        kind: 'cold',
    },
    {
        keyword: 'pyra',
        name: 'Сахарная Пыра',
        price: 5,
        desc: 'Как пирог, только легче воздуха.',
        category: 'dessert',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dessert2.png',
        kind: 'classic',
    },
    {
        keyword: 'semki',
        name: 'Семечковая Нуга',
        price: 6,
        desc: 'Хрустит, как вечер на крыльце.',
        category: 'dessert',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dessert3.png',
        kind: 'classic',
    },
    {
        keyword: 'peremenka',
        name: 'Переменка',
        price: 8,
        desc: 'Хрустит, тает, кислит, жжёт — по кругу.',
        category: 'dessert',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dessert4.png',
        kind: 'odd',
    },
    {
        keyword: 'pugovki',
        name: 'Пуговки',
        price: 7,
        desc: 'Их едят, а они глядят.',
        category: 'dessert',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dessert5.png',
        kind: 'odd',
    },
    {
        keyword: 'provoloka',
        name: 'Сладкая Проволока',
        price: 7,
        desc: 'Тонкая, хрустит, сладость приходит с опозданием.',
        category: 'dessert',
        img: 'https://a-e-skald.github.io/progalina-web/dishes/dessert6.png',
        kind: 'odd',
    },
]